# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16QqatzUSuFGqPPb4p-H8wFY9Wnj9pstt
"""

import pandas as pd

df = pd.read_csv('/content/01.Data Cleaning and Preprocessing.csv')
print("Original DataFrame:\n", df)

# 1. Filtering data based on a condition
# Example: Filter rows where 'ChipRate' is greater than 15
filtered_df = df[df['ChipRate'] > 15]
print("\nDataFrame after filtering rows where ChipRate > 15:\n", filtered_df)

# 2. Handling missing values
# Fill missing values with a default value (e.g., 0)
filled_df = df.fillna(0)
print("\nDataFrame after filling missing values with 0:\n", filled_df)

# Alternatively, drop rows with missing values
dropped_df = df.dropna()
print("\nDataFrame after dropping rows with missing values:\n", dropped_df)

# 3. Calculating summary statistics
# Example: Calculate mean, median, and standard deviation for numerical columns
mean_values = df.mean(numeric_only=True)
median_values = df.median(numeric_only=True)
std_dev_values = df.std(numeric_only=True)

print("\nSummary Statistics:")
print("Mean values:\n", mean_values)
print("Median values:\n", median_values)
print("Standard deviation:\n", std_dev_values)